name: Node.js CI

on: [push]

jobs:
 lint-and-test:
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [16.x, 17.x, 18.x, 19.x, 20.x]

  steps:
   - uses: actions/checkout@v3
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node-version }}
   - run: npm ci
   - run: npm run lint
   - run: npm test
   - name: Upload coverage reports to Codecov
     uses: codecov/codecov-action@v3
     with:
      token: ${{ secrets.CODECOV_TOKEN }}
      file: ./coverage/lcov.info
      flags: unittests
      name: codecov-upload
      # fail_ci_if_error: true
     env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
