name: Publish to NPM
on:
 release:
  types: [published]
jobs:
 publish:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Setup Node
     uses: actions/setup-node@v2
     with:
      node-version: '16.x'
      registry-url: 'https://registry.npmjs.org'
      always-auth: false
      scope: '@niveus'
   - name: Install dependencies  🔧
     run: npm ci
   - name: Publish package on NPM 📦
     run: npm run npm-publish
     env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
   - name: Generate changelog
     id: changelog
     uses: metcalfc/changelog-generator@v4.1.0
     with:
      myToken: ${{ secrets.GITHUB_TOKEN }}
